# Generated by Django 5.1.5 on 2025-04-27 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CandidateProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                (
                    "education_details",
                    models.TextField(
                        help_text="Degrees, Institutions, Years, and CGPA"
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "employment_details",
                    models.TextField(help_text="Year of Experience and Work Done"),
                ),
                (
                    "total_years_of_experience",
                    models.CharField(
                        help_text="Total Experience (Range)", max_length=50
                    ),
                ),
                (
                    "technical_skills",
                    models.TextField(help_text="List of Technical Skills"),
                ),
                ("soft_skills", models.TextField(help_text="List of Soft Skills")),
                (
                    "certifications",
                    models.TextField(
                        blank=True,
                        help_text="List of Certifications, Licenses, Credentials",
                        null=True,
                    ),
                ),
                (
                    "profile_links",
                    models.TextField(
                        blank=True,
                        help_text="Links of Profiles like LinkedIn, GitHub, etc.",
                        null=True,
                    ),
                ),
                (
                    "projects",
                    models.TextField(
                        blank=True,
                        help_text="Details of Projects or Notable Work",
                        null=True,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CandidateEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.IntegerField(
                        blank=True, help_text="Score given during evaluation", null=True
                    ),
                ),
                (
                    "remarks",
                    models.TextField(
                        blank=True, help_text="Remarks on the candidate", null=True
                    ),
                ),
                (
                    "candidate",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluation",
                        to="api.candidateprofile",
                    ),
                ),
            ],
        ),
    ]
